### ISSUE TITLE
[Bug] Not working correctly with Microsoft Edge

### ISSUE THREAD

**Issue by fVargasg** [creativetimofficial/ct-material-dashboard-pro-angular#344] opened 2019-10-20 16:15 UTC
### Version
2.3.0
### Reproduction link
https://demos.creative-tim.com/material-dashboard-pro-angular2/#/dashboard
### Operating System
Windows 10
### Device
pc
### Browser & Version
Microsoft Edge
### Steps to reproduce
na
### What is expected?
na
### What is actually happening?
A lot of errors on the console, sidebar is not working

---

**Comment by chelaruc** [comment] 2019-10-22 06:13
Hi, @fVargasg. Thank you for using our product. 
This is a duplicate of #339

**Closed by chelaruc** 2019-10-22 06:13 UTC
